// Mocks generated by Mockito 5.1.0 from annotations
// in todo_app/test/features/todo/data/repositories/todo_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/features/todo/data/datasources/todo_local_data_source.dart'
    as _i2;
import 'package:todo_app/features/todo/domain/entities/todo.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [TodoLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoLocalDataSource extends _i1.Mock
    implements _i2.TodoLocalDataSource {
  MockTodoLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ToDo>> getAllTodos() =>
      (super.noSuchMethod(Invocation.method(#getAllTodos, []),
              returnValue: Future<List<_i4.ToDo>>.value(<_i4.ToDo>[]))
          as _i3.Future<List<_i4.ToDo>>);
  @override
  _i3.Future<List<_i4.ToDo>> getConditionedTodos(bool? isCompleted) => (super
          .noSuchMethod(Invocation.method(#getConditionedTodos, [isCompleted]),
              returnValue: Future<List<_i4.ToDo>>.value(<_i4.ToDo>[]))
      as _i3.Future<List<_i4.ToDo>>);
  @override
  _i3.Future<void> saveTodo(_i4.ToDo? toDo) =>
      (super.noSuchMethod(Invocation.method(#saveTodo, [toDo]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
